AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/**/*'
    - 'doc/**/*'

Rails:
  Enabled: true

Style/SafeNavigation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Tab:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Max: 90

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150